### ISSUE TITLE
Check a bunch of MD5 from a file ( -c parameter)

### ISSUE THREAD

**Issue by jeroeneck** [eexit/md5checker#1]
Is it possible to have a (linux) like -c parameter : read MD5 sums from the FILEs and check them.

EQ

```
$ cat my_files.tar.gz.md5
2fdd5a63d43d1ee3ed9dc93c783fd7bd  my_file1.tar.gz
d41d8cd98f00b104e9800968ecf8427e  my_file2.tar.gz
$ md5sum -c my_file.tar.gz.md5
my_file1.tar.gz: OK
my_file2.tar.gz: OK
$
```

For a man page of the Linux md5sum see: http://man7.org/linux/man-pages/man1/md5sum.1.html

**Comment by eexit** [comment]
@jeroeneck thanks for your concern.

Not sure if you read the [README](https://github.com/eexit/md5sum/blob/master/README.md) but this is exactly what does the `md5sum` script: it reads from a `MD5SUMS` file (or `my_files.tar.gz.md5`in your example) and parse the md5 sum then compares then with existing files...

**Comment by jeroeneck** [comment]
You are right;
The md5sum in Linux creates a md5 without any parameters and does a check with the -c parameter

As a (mostly command-line) Linux user; I got confused. Your script will be an excellent base to create the Linux like tool. Thanks!

Jeroen
